CPBASE="/cygdrive/c/Users/scarton/.m2/repository"
CLASSPATH="/cygdrive/c/projects/TextClean/target/classes:\
$CPBASE/org/apache/opennlp/opennlp-tools/1.6.0/opennlp-tools-1.6.0.jar:\
$CPBASE/org/apache/opennlp/opennlp-uima/1.6.0/opennlp-uima-1.6.0.jar:\
$CPBASE/edu/stanford/nlp/stanford-corenlp/3.5.2/stanford-corenlp-3.5.2.jar:\
$CPBASE/com/io7m/xom/xom/1.2.10/xom-1.2.10.jar:\
$CPBASE/xml-apis/xml-apis/1.3.03/xml-apis-1.3.03.jar:\
$CPBASE/xerces/xercesImpl/2.8.0/xercesImpl-2.8.0.jar:\
$CPBASE/xalan/xalan/2.7.0/xalan-2.7.0.jar:\
$CPBASE/joda-time/joda-time/2.1/joda-time-2.1.jar:\
$CPBASE/de/jollyday/jollyday/0.4.7/jollyday-0.4.7.jar:\
$CPBASE/javax/xml/bind/jaxb-api/2.2.7/jaxb-api-2.2.7.jar:\
$CPBASE/com/googlecode/efficient-java-matrix-library/ejml/0.23/ejml-0.23.jar:\
$CPBASE/javax/json/javax.json-api/1.0/javax.json-api-1.0.jar:\
$CPBASE/edu/stanford/nlp/stanford-corenlp/3.5.2/stanford-corenlp-3.5.2-models.jar:\
$CPBASE/com/thoughtworks/xstream/xstream/1.4.8/xstream-1.4.8.jar:\
$CPBASE/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.jar:\
$CPBASE/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar:\
$CPBASE/net/sf/jtidy/jtidy/r938/jtidy-r938.jar:\
$CPBASE/org/apache/tika/tika-core/1.11/tika-core-1.11.jar:\
$CPBASE/org/apache/lucene/lucene-analyzers-common/5.3.0/lucene-analyzers-common-5.3.0.jar:\
$CPBASE/org/apache/lucene/lucene-core/5.3.0/lucene-core-5.3.0.jar:\
$CPBASE/com/googlecode/json-simple/json-simple/1.1/json-simple-1.1.jar:\
$CPBASE/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:\
$CPBASE/commons-io/commons-io/2.4/commons-io-2.4.jar:\
$CPBASE/org/jsoup/jsoup/1.8.3/jsoup-1.8.3.jar:\
$CPBASE/org/slf4j/jcl-over-slf4j/1.7.12/jcl-over-slf4j-1.7.12.jar:\
$CPBASE/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.jar:\
$CPBASE/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar:\
$CPBASE/ch/qos/logback/logback-core/1.1.3/logback-core-1.1.3.jar"